name: "Generate Release Page"
author: "Keren Dong"
description: "Generate Release Page for Kungfu Products"
inputs:
  token:
    description: "GitHub token"
  product:
    description: "Kungfu Product"
    default: "kungfu-trader"
  release-path:
    description: "Release Path for URL"
    default: "static"
runs:
  using: "node16"
  main: "dist/index.js"
