name: "Generate Release Page"
author: "Keren Dong"
description: "Generate Release Page for Kungfu Products"
inputs:
  token:
    description: "GitHub token"
  repo:
    description: "Do not add comment to GitHub [true/false]"
    default: "false"
  preview-files:
    description: "Pattern for preview file names"
    default: ".*"
  max-preview-links:
    description: "Max number of preview links"
    default: "32"
runs:
  using: "node16"
  main: "dist/index.js"
