name: Sync - Release Page
on:
  workflow_dispatch:
    inputs:
      product:
        description: 'Type product name to generate release page'
        required: true
        default: 'kungfu-trader'
      release-path:
        description: 'Type product name to generate release page'
        required: true
        default: 'static'
      lower-edge:
        description: 'filter version >= lower-edge value'
        required: false
      upper-edge:
        description: 'filter version <= upper-edge value'
        required: false
      release-url:
          description: 'release page base url'
          default: 'https://releases.kungfu-trader.com'
          required: true

jobs:
  sync-release-page:
    uses: kungfu-trader/workflows/.github/workflows/.sync-release-page.yml@dev/v1/v1.2
    with:
      product: ${{ github.event.inputs.product }}
      release-path: ${{ github.event.inputs.release-path }}
      lower-edge: ${{ github.event.inputs.lower-edge }}
      upper-edge: ${{ github.event.inputs.upper-edge }}
      release-url: ${{ github.event.inputs.release-url }}